function run_all_tests(log_path)
%RUN_ALL_TESTS  Run the full self-checking regression suite and write a
%   reproducible log file.
%
%   RUN_ALL_TESTS() writes to the default log path
%       tests/run_all_tests_log.txt
%   (relative to this file's own directory, regardless of current
%   working directory).
%
%   RUN_ALL_TESTS(log_path) writes to a custom path instead.
%
%   REPRODUCIBILITY: every seeded random test in this suite uses a
%   fixed rand('seed', ...) value:
%       test_dwt53_1d.m              seed=12345
%       test_dwt53_2d.m              seed=777
%       test_dwt53_2level.m          seed=2026
%       test_export_golden_vectors.m seed=4040
%       test_export_packed_planes.m  seed=5150
%   so re-running this function on the SAME platform (MATLAB or Octave)
%   reproduces byte-identical case counts, coefficient ranges, and
%   pass/fail results every time. Only the wall-clock "Elapsed time"
%   line and the "Generated at" timestamp in the log header will differ
%   between runs -- everything else is deterministic given the seeds
%   above. (Note: MATLAB and Octave use different legacy RNG algorithms
%   behind rand('seed', N), so the exact random vectors -- and therefore
%   things like the observed coefficient range -- can still differ
%   between MATLAB and Octave even at the same seed value; they will
%   NOT differ between repeated runs on the same platform.)
%
%   Wiring: floor_divide_int, 1D forward/inverse, one-level 2D
%   forward/inverse + pack/unpack, two-level 2D forward/inverse +
%   pack/unpack, and the golden-vector export + readback round trip
%   (GATE_1 through GATE_4), plus the packed C1/C2 plane export that the
%   RTL regression consumes via $readmemh.

    this_dir = fileparts(mfilename('fullpath'));
    addpath(this_dir);
    addpath(fullfile(this_dir, '..'));

    if nargin < 1 || isempty(log_path)
        log_path = fullfile(this_dir, 'run_all_tests_log.txt');
    end

    % diary() mirrors every fprintf/disp below into log_path AS WELL AS
    % the console, so the log file is generated by this function itself
    % -- no external shell redirection (e.g. "octave --eval ... > log.txt")
    % is required for a reproducible artifact.
    if exist(log_path, 'file')
        delete(log_path);
    end
    diary(log_path);
    diary on;
    cleanup_diary = onCleanup(@() diary('off'));  % closes diary even if a test errors out

    fprintf('##########################################\n');
    fprintf('# DWT53 Golden Model - Regression Suite\n');
    fprintf('# Scope: GATE_1 + GATE_2 + GATE_3 + GATE_4\n');
    fprintf('# Generated at   : %s\n', datestr(now));
    if exist('OCTAVE_VERSION', 'builtin')
        fprintf('# Runtime        : Octave %s\n', OCTAVE_VERSION);
    else
        fprintf('# Runtime        : MATLAB %s\n', version);
    end
    fprintf('# Platform       : %s\n', computer());
    fprintf('# Log file       : %s\n', log_path);
    fprintf('# Seeds (fixed)  : 1D=12345  2D=777  2level=2026  export=4040  packed=5150\n');
    fprintf('#\n');
    fprintf('# SOURCE FINGERPRINT -- which snapshot produced this log\n');
    fprintf('# Format: <hash1>-<hash2>-<bytes>.  Two independent weighted byte\n');
    fprintf('# sums plus the byte count.  NOT cryptographic: it detects an edited\n');
    fprintf('# or swapped file, it does not resist a deliberate forgery.  Its job\n');
    fprintf('# is to stop a PASS log being paired with the wrong source snapshot.\n');
    print_fingerprints(this_dir);
    fprintf('##########################################\n\n');

    t_start = tic;

    fprintf('[1/7] floor_divide_int ...........................\n');
    test_floor_divide_int();
    fprintf('\n');

    fprintf('[2/7] dwt53_forward_1d / dwt53_inverse_1d ........\n');
    stats1d = test_dwt53_1d();
    fprintf('\n');

    fprintf('[3/7] dwt53_forward_2d / dwt53_inverse_2d ........\n');
    stats2d = test_dwt53_2d();
    fprintf('\n');

    fprintf('[4/7] dwt53_forward_2level / dwt53_inverse_2level \n');
    stats2level = test_dwt53_2level();
    fprintf('\n');

    fprintf('[5/7] int_to_hex_signed / hex_signed_to_int ......\n');
    n_hex_pass = test_int_hex_signed();
    fprintf('\n');

    fprintf('[6/7] export_golden_vectors (readback round trip) \n');
    n_export_pass = test_export_golden_vectors();
    fprintf('\n');

    fprintf('[7/7] export_packed_planes (packed C1/C2 readback) ..\n');
    n_packed_pass = test_export_packed_planes();
    fprintf('\n');

    t_elapsed = toc(t_start);

    % T-09: every gate line below is printed from a status VARIABLE, not from
    % a literal "PASS" string.  A gate is marked passed only if its test
    % returned and its own numeric acceptance criterion holds here.  A literal
    % would still print PASS if someone later wrapped a test in try/catch.
    gate1_ok = (stats1d.max_abs_recon_error    == 0) && (stats1d.n_cases     > 0);
    gate2_ok = (stats2d.max_abs_recon_error    == 0) && (stats2d.n_cases     > 0);
    gate3_ok = (stats2level.max_abs_recon_error == 0) && (stats2level.n_cases > 0);
    gate4_ok = (n_hex_pass    > 0) && (n_export_pass > 0);
    packed_ok = (n_packed_pass > 0);
    all_ok   = gate1_ok && gate2_ok && gate3_ok && gate4_ok && packed_ok;

    fprintf('##########################################\n');
    fprintf('# GATE 1 RESULT: %s\n', verdict(gate1_ok));
    fprintf('# Total 1D cases           : %d\n', stats1d.n_cases);
    fprintf('# Max reconstruction error : %d\n', double(stats1d.max_abs_recon_error));
    fprintf('# Coefficient range (PLAT) : [%d, %d]\n', ...
        double(stats1d.min_coeff), double(stats1d.max_coeff));
    fprintf('#\n');
    fprintf('# GATE 2 RESULT: %s\n', verdict(gate2_ok));
    fprintf('# Total 2D cases           : %d\n', stats2d.n_cases);
    fprintf('# Max reconstruction error : %d\n', double(stats2d.max_abs_recon_error));
    fprintf('# Coefficient range (PLAT) : [%d, %d]\n', ...
        double(stats2d.min_coeff), double(stats2d.max_coeff));
    fprintf('#\n');
    fprintf('# GATE 3 RESULT: %s\n', verdict(gate3_ok));
    fprintf('# Total 2-level cases      : %d\n', stats2level.n_cases);
    fprintf('# Max reconstruction error : %d\n', double(stats2level.max_abs_recon_error));
    fprintf('# Coefficient range (PLAT) : [%d, %d]\n', ...
        double(stats2level.min_coeff), double(stats2level.max_coeff));
    fprintf('#\n');
    fprintf('# GATE 4 RESULT: %s\n', verdict(gate4_ok));
    fprintf('# hex helper assertions    : %d\n', n_hex_pass);
    fprintf('# export/readback asserts  : %d\n', n_export_pass);
    fprintf('#\n');
    fprintf('# PACKED PLANE EXPORT: %s\n', verdict(packed_ok));
    fprintf('# packed C1/C2 asserts      : %d\n', n_packed_pass);
    fprintf('#\n');
    fprintf('# Elapsed time             : %.1f s\n', t_elapsed);
    fprintf('# Log written to           : %s\n', log_path);
    fprintf('#\n');
    fprintf('# ACCEPTANCE CRITERIA -- which numbers above are portable\n');
    fprintf('# INVARIANT across MATLAB and Octave, compare these between runs:\n');
    fprintf('#   every case count, every max reconstruction error, every gate\n');
    fprintf('#   verdict, and every assertion count.\n');
    fprintf('# PLATFORM DEPENDENT, do NOT use as an acceptance criterion:\n');
    fprintf('#   the lines marked (PLAT).  rand(''seed'',N) drives a different\n');
    fprintf('#   legacy generator in MATLAB and in Octave, so the random content\n');
    fprintf('#   -- and therefore the observed coefficient range -- differs even\n');
    fprintf('#   at an identical seed.  Repeated runs on the SAME runtime are\n');
    fprintf('#   byte identical apart from timestamps and elapsed time.\n');
    fprintf('#\n');
    fprintf('# OVERALL: %s\n', verdict(all_ok));
    fprintf('##########################################\n');

    if ~all_ok
        error('run_all_tests:gateFailed', ...
            'One or more gates did not meet their acceptance criterion.');
    end

    % cleanup_diary's destructor runs "diary off" automatically when
    % this function returns (or errors) and the variable goes out of
    % scope -- see onCleanup above.
end

% =====================================================================
% Local helper subfunctions
% =====================================================================

function v = verdict(ok)
    if ok
        v = 'PASS';
    else
        v = 'FAIL';
    end
end

function print_fingerprints(tests_dir)
% Print a fingerprint line for every source file the suite depends on, so a
% transcript can never be paired with the wrong snapshot by accident.
    model_dir = fullfile(tests_dir, '..');
    model_files = { ...
        'floor_divide_int.m', 'int_to_hex_signed.m', 'hex_signed_to_int.m', ...
        'dwt53_forward_1d.m', 'dwt53_inverse_1d.m', ...
        'dwt53_forward_2d.m', 'dwt53_inverse_2d.m', ...
        'dwt53_forward_2level.m', 'dwt53_inverse_2level.m', ...
        'dwt53_pack_2d.m', 'dwt53_unpack_2d.m', ...
        'dwt53_pack_2level.m', 'dwt53_unpack_2level.m', ...
        'export_golden_vectors.m', 'export_golden_vectors_1d.m', ...
        'export_packed_planes.m', 'gen_golden_vectors.m'};
    test_files = { ...
        'run_all_tests.m', 'test_floor_divide_int.m', 'test_dwt53_1d.m', ...
        'test_dwt53_2d.m', 'test_dwt53_2level.m', 'test_int_hex_signed.m', ...
        'test_export_golden_vectors.m', 'test_export_packed_planes.m'};

    for i = 1:numel(model_files)
        fprintf('#   %-28s %s\n', model_files{i}, ...
            file_fingerprint(fullfile(model_dir, model_files{i})));
    end
    for i = 1:numel(test_files)
        fprintf('#   tests/%-22s %s\n', test_files{i}, ...
            file_fingerprint(fullfile(tests_dir, test_files{i})));
    end
    fprintf('#   %-28s %s\n', 'test_data/real_frame.png', ...
        file_fingerprint(fullfile(model_dir, 'test_data', 'real_frame_1280x720.png')));
end

function s = file_fingerprint(path)
    fid = fopen(path, 'r');
    if fid < 0
        s = 'MISSING';
        return;
    end
    b = fread(fid, Inf, 'uint8=>double');
    fclose(fid);
    n = numel(b);
    if n == 0
        s = '00000000-00000000-0';
        return;
    end
    idx = (1:n)';
    h1 = mod(sum(b .* mod(idx, 251))   + n * 7919,   2^32);
    h2 = mod(sum(b .* mod(idx, 65521)) + n * 104729, 2^32);
    s = sprintf('%08X-%08X-%d', h1, h2, n);
end
